kind = "mobile"
previewPath = "/"
title = "Alarm App"
version = "1.0.0"
id = "artifacts/alarm-app"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 25822

[services.development]
run = "pnpm --filter @workspace/alarm-app run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/alarm-app", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/alarm-app", "run", "serve" ]

[services.env]
PORT = "25822"
BASE_PATH = "/"
